CREATE  TABLE EMPLOYEE(
    EMP_ID BIGINT NOT NULL,
    EMAIL_ID VARCHAR(255),
    FOOD_PREFERENCE INTEGER,
    GENDER INTEGER,
    MOBILE VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PHOTO VARCHAR(10485760),
    PROJECT_NAME VARCHAR(255),
    REGISTRATION_NO BIGINT,
    SHIRT_SIZE INTEGER
)

CREATE  TABLE FLIGHT_INFO(
    ID INTEGER,
    AIRLINE_NAME VARCHAR(255),
    ARRIVAL_DATE VARCHAR(255),
    ARRIVAL_TIME VARCHAR(255),
    DEST_LOCATION VARCHAR(255),
    FLIGHT_NUMBER VARCHAR(255),
    SRC_LOCATION VARCHAR(255),
    EMP_ID BIGINT
)

CREATE  TABLE PHOTOGRAPHY_CONTEST_RESPONSE(
    EMP_ID BIGINT,
    IMAGE_ID INTEGER,
    COMMENT VARCHAR(255),
    TIME_STAMP TIMESTAMP,
    VOTE INTEGER
)

CREATE  TABLE PHOTOGRAPHY_CONTEST_IMAGE(
    IMAGE_ID INTEGER,
    CONTENT VARCHAR(255),
    IMAGE_NAME VARCHAR(255),
    OWNER VARCHAR(255)
)

CREATE  TABLE EVENT(
    EVENT_ID INTEGER,
    EVENT_DETAILS VARCHAR(255),
    DURATION VARCHAR(255),
    END VARCHAR(255),
    EVENT_NAME VARCHAR(255),
    PHOTO VARCHAR(255),
    PPT_PATH VARCHAR(255),
    START VARCHAR(255),
    STATE INTEGER
)

CREATE  TABLE QUESTION(
    QUESTION_ID VARCHAR(255),
    CURRENT BOOLEAN,
    OPTION_A VARCHAR(255),
    OPTION_B VARCHAR(255),
    OPTION_C VARCHAR(255),
    OPTION_CORRECT VARCHAR(255),
    OPTION_D VARCHAR(255),
    QUESTION_TEXT VARCHAR(255)
)
CREATE  TABLE EVENT_RESPONSE(
    EMP_ID BIGINT,
    EVENT_ID INTEGER,
    COMMENT VARCHAR(255),
    TIME_STAMP TIMESTAMP,
    VOTE INTEGER
)

CREATE  TABLE QUIZ_RESPONSE(
    EMP_ID BIGINT,
    QUESTION_ID VARCHAR(255),
    OPTION_SELECTED VARCHAR(255),
    TIME_STAMP TIMESTAMP
)